#!/bin/bash
#SBATCH -p defq
#SBATCH --time=120:00
set -e
cd /data/abattle4/lab_data/GWAS_summary_statistics/FinnGen
wget -O GWAS_colon_adenocarcinoma_FinnGen_C3_COLON_ADENO_EXALLC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_COLON_ADENO_EXALLC.gz
wget -O GWAS_colon_adenocarcinoma_FinnGen_C3_COLON_ADENO_EXALLC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_COLON_ADENO_EXALLC.gz.tbi
wget -O GWAS_hallux_valgus_FinnGen_M13_HALLUXVALGUS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_HALLUXVALGUS.gz
wget -O GWAS_hallux_valgus_FinnGen_M13_HALLUXVALGUS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_HALLUXVALGUS.gz.tbi
wget -O GWAS_ulcerative_colitis_FinnGen_K11_UC_STRICT2.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_UC_STRICT2.gz
wget -O GWAS_ulcerative_colitis_FinnGen_K11_UC_STRICT2.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_UC_STRICT2.gz.tbi
wget -O GWAS_actinic_keratosis_FinnGen_L12_ACTINKERA.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_L12_ACTINKERA.gz
wget -O GWAS_actinic_keratosis_FinnGen_L12_ACTINKERA.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_L12_ACTINKERA.gz.tbi
wget -O GWAS_appendicitis_acute_FinnGen_K11_APPENDACUT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_APPENDACUT.gz
wget -O GWAS_appendicitis_acute_FinnGen_K11_APPENDACUT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_APPENDACUT.gz.tbi
wget -O GWAS_renal_failure_acute_FinnGen_N14_ACUTERENFAIL.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_ACUTERENFAIL.gz
wget -O GWAS_renal_failure_acute_FinnGen_N14_ACUTERENFAIL.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_ACUTERENFAIL.gz.tbi
wget -O GWAS_alcoholism_FinnGen_AUD.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AUD.gz
wget -O GWAS_alcoholism_FinnGen_AUD.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AUD.gz.tbi
wget -O GWAS_anxiety_disorders_FinnGen_F5_ALLANXIOUS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_ALLANXIOUS.gz
wget -O GWAS_anxiety_disorders_FinnGen_F5_ALLANXIOUS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_ALLANXIOUS.gz.tbi
wget -O GWAS_angina_pectoris_FinnGen_I9_ANGINA.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_ANGINA.gz
wget -O GWAS_angina_pectoris_FinnGen_I9_ANGINA.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_ANGINA.gz.tbi
wget -O GWAS_asthma_FinnGen_J10_ASTHMA_MAIN_EXMORE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_ASTHMA_MAIN_EXMORE.gz
wget -O GWAS_asthma_FinnGen_J10_ASTHMA_MAIN_EXMORE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_ASTHMA_MAIN_EXMORE.gz.tbi
wget -O GWAS_atrial_fibrillation_FinnGen_I9_AF.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_AF.gz
wget -O GWAS_atrial_fibrillation_FinnGen_I9_AF.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_AF.gz.tbi
wget -O GWAS_bacterial_infection_other_FinnGen_AB1_BACTINF_NOS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AB1_BACTINF_NOS.gz
wget -O GWAS_bacterial_infection_other_FinnGen_AB1_BACTINF_NOS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AB1_BACTINF_NOS.gz.tbi
wget -O GWAS_bacterial_pnumonia_FinnGen_J10_PNEUMOBACT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_PNEUMOBACT.gz
wget -O GWAS_bacterial_pnumonia_FinnGen_J10_PNEUMOBACT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_PNEUMOBACT.gz.tbi
wget -O GWAS_mammary_displasia_benign_FinnGen_N14_BENIGNMAMDYSP.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_BENIGNMAMDYSP.gz
wget -O GWAS_mammary_displasia_benign_FinnGen_N14_BENIGNMAMDYSP.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_BENIGNMAMDYSP.gz.tbi
wget -O GWAS_colon_neoplasm_benign_FinnGen_CD2_BENIGN_COLON.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CD2_BENIGN_COLON.gz
wget -O GWAS_colon_neoplasm_benign_FinnGen_CD2_BENIGN_COLON.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CD2_BENIGN_COLON.gz.tbi
wget -O GWAS_cardiac_arrhythmias_FinnGen_CARDIAC_ARRHYTM.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CARDIAC_ARRHYTM.gz
wget -O GWAS_cardiac_arrhythmias_FinnGen_CARDIAC_ARRHYTM.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CARDIAC_ARRHYTM.gz.tbi
wget -O GWAS_cholelithiasis_FinnGen_K11_CHOLELITH.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_CHOLELITH.gz
wget -O GWAS_cholelithiasis_FinnGen_K11_CHOLELITH.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_CHOLELITH.gz.tbi
wget -O GWAS_chronic_kidney_disease_FinnGen_N14_CHRONKIDNEYDIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_CHRONKIDNEYDIS.gz
wget -O GWAS_chronic_kidney_disease_FinnGen_N14_CHRONKIDNEYDIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_CHRONKIDNEYDIS.gz.tbi
wget -O GWAS_chronic_sinusitis_FinnGen_J10_CHRONSINUSITIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_CHRONSINUSITIS.gz
wget -O GWAS_chronic_sinusitis_FinnGen_J10_CHRONSINUSITIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_CHRONSINUSITIS.gz.tbi
wget -O GWAS_colorectal_cancer_FinnGen_C3_COLORECTAL_EXALLC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_COLORECTAL_EXALLC.gz
wget -O GWAS_colorectal_cancer_FinnGen_C3_COLORECTAL_EXALLC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_COLORECTAL_EXALLC.gz.tbi
wget -O GWAS_constipation_FinnGen_K11_CONSTIPATION.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_CONSTIPATION.gz
wget -O GWAS_constipation_FinnGen_K11_CONSTIPATION.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_CONSTIPATION.gz.tbi
wget -O GWAS_coronary_atherosclerosis_FinnGen_I9_CORATHER.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_CORATHER.gz
wget -O GWAS_coronary_atherosclerosis_FinnGen_I9_CORATHER.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_CORATHER.gz.tbi
wget -O GWAS_cystitis_FinnGen_N14_CYSTITIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_CYSTITIS.gz
wget -O GWAS_cystitis_FinnGen_N14_CYSTITIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_CYSTITIS.gz.tbi
wget -O GWAS_depression_FinnGen_F5_DEPRESSIO.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_DEPRESSIO.gz
wget -O GWAS_depression_FinnGen_F5_DEPRESSIO.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_DEPRESSIO.gz.tbi
wget -O GWAS_diaphragmatic_hernia_FinnGen_K11_DIAHER.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DIAHER.gz
wget -O GWAS_diaphragmatic_hernia_FinnGen_K11_DIAHER.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DIAHER.gz.tbi
wget -O GWAS_lipoprotein_metabolism_disorders_FinnGen_E4_LIPOPROT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_E4_LIPOPROT.gz
wget -O GWAS_lipoprotein_metabolism_disorders_FinnGen_E4_LIPOPROT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_E4_LIPOPROT.gz.tbi
wget -O GWAS_intestinal_diverticular_disease_FinnGen_K11_DIVERTIC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DIVERTIC.gz
wget -O GWAS_intestinal_diverticular_disease_FinnGen_K11_DIVERTIC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DIVERTIC.gz.tbi
wget -O GWAS_duodenal_ulcer_FinnGen_K11_DULC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DULC.gz
wget -O GWAS_duodenal_ulcer_FinnGen_K11_DULC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_DULC.gz.tbi
wget -O GWAS_endometriosis_FinnGen_N14_ENDOMETRIOSIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_ENDOMETRIOSIS.gz
wget -O GWAS_endometriosis_FinnGen_N14_ENDOMETRIOSIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_ENDOMETRIOSIS.gz.tbi
wget -O GWAS_fracture_at_wrist_and_hand_level_FinnGen_ST19_FRACT_WRIST_HAND_LEVEL.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_ST19_FRACT_WRIST_HAND_LEVEL.gz
wget -O GWAS_fracture_at_wrist_and_hand_level_FinnGen_ST19_FRACT_WRIST_HAND_LEVEL.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_ST19_FRACT_WRIST_HAND_LEVEL.gz.tbi
wget -O GWAS_gastric_ulcer_FinnGen_K11_GULC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_GULC.gz
wget -O GWAS_gastric_ulcer_FinnGen_K11_GULC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_GULC.gz.tbi
wget -O GWAS_gastroduodenal_ulcer_FinnGen_K11_GASTRODUOULC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_GASTRODUOULC.gz
wget -O GWAS_gastroduodenal_ulcer_FinnGen_K11_GASTRODUOULC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_GASTRODUOULC.gz.tbi
wget -O GWAS_glaucoma_FinnGen_H7_GLAUCOMA.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_GLAUCOMA.gz
wget -O GWAS_glaucoma_FinnGen_H7_GLAUCOMA.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_GLAUCOMA.gz.tbi
wget -O GWAS_gout_FinnGen_M13_GOUT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_GOUT.gz
wget -O GWAS_gout_FinnGen_M13_GOUT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_GOUT.gz.tbi
wget -O GWAS_abdominal_hernia_FinnGen_ABDOM_HERNIA.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_ABDOM_HERNIA.gz
wget -O GWAS_abdominal_hernia_FinnGen_ABDOM_HERNIA.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_ABDOM_HERNIA.gz.tbi
wget -O GWAS_hypertension_FinnGen_I9_HYPTENS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_HYPTENS.gz
wget -O GWAS_hypertension_FinnGen_I9_HYPTENS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_HYPTENS.gz.tbi
wget -O GWAS_inflammatory_bowel_disease_FinnGen_K11_IBD_STRICT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_IBD_STRICT.gz
wget -O GWAS_inflammatory_bowel_disease_FinnGen_K11_IBD_STRICT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_IBD_STRICT.gz.tbi
wget -O GWAS_inflammatory_diseases_of_female_pelvic_organs_FinnGen_N14_FEMALEGENINF.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_FEMALEGENINF.gz
wget -O GWAS_inflammatory_diseases_of_female_pelvic_organs_FinnGen_N14_FEMALEGENINF.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_FEMALEGENINF.gz.tbi
wget -O GWAS_inguinal_hernia_FinnGen_K11_HERING.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_HERING.gz
wget -O GWAS_inguinal_hernia_FinnGen_K11_HERING.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_HERING.gz.tbi
wget -O GWAS_internal_derangement_of_knee_FinnGen_M13_KNEEDERANGEMENTS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_KNEEDERANGEMENTS.gz
wget -O GWAS_internal_derangement_of_knee_FinnGen_M13_KNEEDERANGEMENTS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_KNEEDERANGEMENTS.gz.tbi
wget -O GWAS_intestinal_infectious_diseases_FinnGen_AB1_INTESTINAL_INFECTIONS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AB1_INTESTINAL_INFECTIONS.gz
wget -O GWAS_intestinal_infectious_diseases_FinnGen_AB1_INTESTINAL_INFECTIONS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_AB1_INTESTINAL_INFECTIONS.gz.tbi
wget -O GWAS_ischaemic_heart_disease_FinnGen_I9_IHD.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_IHD.gz
wget -O GWAS_ischaemic_heart_disease_FinnGen_I9_IHD.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_IHD.gz.tbi
wget -O GWAS_uterine_leiomyoma_FinnGen_CD2_BENIGN_LEIOMYOMA_UTERI.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CD2_BENIGN_LEIOMYOMA_UTERI.gz
wget -O GWAS_uterine_leiomyoma_FinnGen_CD2_BENIGN_LEIOMYOMA_UTERI.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_CD2_BENIGN_LEIOMYOMA_UTERI.gz.tbi
wget -O GWAS_neoplasm_of_breast_malignant_FinnGen_C3_BREAST_EXALLC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_BREAST_EXALLC.gz
wget -O GWAS_neoplasm_of_breast_malignant_FinnGen_C3_BREAST_EXALLC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_C3_BREAST_EXALLC.gz.tbi
wget -O GWAS_migraine_FinnGen_G6_MIGRAINE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_MIGRAINE.gz
wget -O GWAS_migraine_FinnGen_G6_MIGRAINE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_MIGRAINE.gz.tbi
wget -O GWAS_mood_disorders_FinnGen_F5_MOOD.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_MOOD.gz
wget -O GWAS_mood_disorders_FinnGen_F5_MOOD.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_F5_MOOD.gz.tbi
wget -O GWAS_myocardial_infarction_FinnGen_I9_MI_STRICT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_MI_STRICT.gz
wget -O GWAS_myocardial_infarction_FinnGen_I9_MI_STRICT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_MI_STRICT.gz.tbi
wget -O GWAS_nasal_polyps_FinnGen_J10_NASALPOLYP.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_NASALPOLYP.gz
wget -O GWAS_nasal_polyps_FinnGen_J10_NASALPOLYP.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_J10_NASALPOLYP.gz.tbi
wget -O GWAS_disorders_of_female_genital_tract_noninflammatory_FinnGen_N14_FEMALEGENNONINF.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_FEMALEGENNONINF.gz
wget -O GWAS_disorders_of_female_genital_tract_noninflammatory_FinnGen_N14_FEMALEGENNONINF.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_FEMALEGENNONINF.gz.tbi
wget -O GWAS_obesity_FinnGen_E4_OBESITY.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_E4_OBESITY.gz
wget -O GWAS_obesity_FinnGen_E4_OBESITY.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_E4_OBESITY.gz.tbi
wget -O GWAS_osteoporosis_FinnGen_M13_OSTEOPOROSIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_OSTEOPOROSIS.gz
wget -O GWAS_osteoporosis_FinnGen_M13_OSTEOPOROSIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_OSTEOPOROSIS.gz.tbi
wget -O GWAS_anaemias_unspecified_FinnGen_D3_ANAEMIANAS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_D3_ANAEMIANAS.gz
wget -O GWAS_anaemias_unspecified_FinnGen_D3_ANAEMIANAS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_D3_ANAEMIANAS.gz.tbi
wget -O GWAS_eyelid_disorders_other_FinnGen_H7_EYELIDDIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_EYELIDDIS.gz
wget -O GWAS_eyelid_disorders_other_FinnGen_H7_EYELIDDIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_EYELIDDIS.gz.tbi
wget -O GWAS_penis_disorders_other_FinnGen_N14_OTHPENIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_OTHPENIS.gz
wget -O GWAS_penis_disorders_other_FinnGen_N14_OTHPENIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_OTHPENIS.gz.tbi
wget -O GWAS_headache_syndromes_other_FinnGen_G6_HEADACHE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_HEADACHE.gz
wget -O GWAS_headache_syndromes_other_FinnGen_G6_HEADACHE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_HEADACHE.gz.tbi
wget -O GWAS_retinal_disorders_other_FinnGen_H7_RETINALDISOTH.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_RETINALDISOTH.gz
wget -O GWAS_retinal_disorders_other_FinnGen_H7_RETINALDISOTH.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_RETINALDISOTH.gz.tbi
wget -O GWAS_ovarian_cyst_FinnGen_N14_OVARYCYST.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_OVARYCYST.gz
wget -O GWAS_ovarian_cyst_FinnGen_N14_OVARYCYST.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_OVARYCYST.gz.tbi
wget -O GWAS_pain_in_joint_FinnGen_JOINTPAIN.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_JOINTPAIN.gz
wget -O GWAS_pain_in_joint_FinnGen_JOINTPAIN.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_JOINTPAIN.gz.tbi
wget -O GWAS_pain_in_limb_FinnGen_M13_LIMBPAIN.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_LIMBPAIN.gz
wget -O GWAS_pain_in_limb_FinnGen_M13_LIMBPAIN.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_LIMBPAIN.gz.tbi
wget -O GWAS_paroxysmal_tachycardia_FinnGen_I9_PAROXTAC.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_PAROXTAC.gz
wget -O GWAS_paroxysmal_tachycardia_FinnGen_I9_PAROXTAC.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_PAROXTAC.gz.tbi
wget -O GWAS_phlebitis_and_thrombophlebitis_FinnGen_I9_PHLETHROM.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_PHLETHROM.gz
wget -O GWAS_phlebitis_and_thrombophlebitis_FinnGen_I9_PHLETHROM.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_PHLETHROM.gz.tbi
wget -O GWAS_female_genital_polyp_FinnGen_N14_POLYPFEMGEN.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_POLYPFEMGEN.gz
wget -O GWAS_female_genital_polyp_FinnGen_N14_POLYPFEMGEN.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_POLYPFEMGEN.gz.tbi
wget -O GWAS_postmenopausal_bleeding_FinnGen_N14_POSTMENBLEED.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_POSTMENBLEED.gz
wget -O GWAS_postmenopausal_bleeding_FinnGen_N14_POSTMENBLEED.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_POSTMENBLEED.gz.tbi
wget -O GWAS_renal_failure_FinnGen_N14_RENFAIL.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_RENFAIL.gz
wget -O GWAS_renal_failure_FinnGen_N14_RENFAIL.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_N14_RENFAIL.gz.tbi
wget -O GWAS_rheumatoid_arthritis_FinnGen_M13_RHEUMA.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_RHEUMA.gz
wget -O GWAS_rheumatoid_arthritis_FinnGen_M13_RHEUMA.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_RHEUMA.gz.tbi
wget -O GWAS_seborrhoeic_keratosis_FinnGen_L12_SEBORRKERAT.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_L12_SEBORRKERAT.gz
wget -O GWAS_seborrhoeic_keratosis_FinnGen_L12_SEBORRKERAT.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_L12_SEBORRKERAT.gz.tbi
wget -O GWAS_senile_cataract_FinnGen_H7_CATARACTSENILE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_CATARACTSENILE.gz
wget -O GWAS_senile_cataract_FinnGen_H7_CATARACTSENILE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_H7_CATARACTSENILE.gz.tbi
wget -O GWAS_sleep_apnoea_FinnGen_G6_SLEEPAPNO.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_SLEEPAPNO.gz
wget -O GWAS_sleep_apnoea_FinnGen_G6_SLEEPAPNO.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_G6_SLEEPAPNO.gz.tbi
wget -O GWAS_sleep_disorders_FinnGen_SLEEP.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_SLEEP.gz
wget -O GWAS_sleep_disorders_FinnGen_SLEEP.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_SLEEP.gz.tbi
wget -O GWAS_spinal_stenosis_FinnGen_M13_SPINSTENOSIS.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_SPINSTENOSIS.gz
wget -O GWAS_spinal_stenosis_FinnGen_M13_SPINSTENOSIS.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_M13_SPINSTENOSIS.gz.tbi
wget -O GWAS_type_1_diabetes_FinnGen_T1D_WIDE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T1D_WIDE.gz
wget -O GWAS_type_1_diabetes_FinnGen_T1D_WIDE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T1D_WIDE.gz.tbi
wget -O GWAS_type_2_diabetes_FinnGen_T2D.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T2D.gz
wget -O GWAS_type_2_diabetes_FinnGen_T2D.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T2D.gz.tbi
wget -O GWAS_type_2_diabetes_FinnGen_T2D_WIDE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T2D_WIDE.gz
wget -O GWAS_type_2_diabetes_FinnGen_T2D_WIDE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T2D_WIDE.gz.tbi
wget -O GWAS_type1_diabetes_FinnGen_T1D.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T1D.gz
wget -O GWAS_type1_diabetes_FinnGen_T1D.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_T1D.gz.tbi
wget -O GWAS_umbilical_hernia_FinnGen_K11_UMBHER.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_UMBHER.gz
wget -O GWAS_umbilical_hernia_FinnGen_K11_UMBHER.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_UMBHER.gz.tbi
wget -O GWAS_unstable_angina_pectoris_FinnGen_I9_UAP.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_UAP.gz
wget -O GWAS_unstable_angina_pectoris_FinnGen_I9_UAP.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_UAP.gz.tbi
wget -O GWAS_varicose_veins_FinnGen_I9_VARICVE.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_VARICVE.gz
wget -O GWAS_varicose_veins_FinnGen_I9_VARICVE.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_I9_VARICVE.gz.tbi
wget -O GWAS_ventral_hernia_FinnGen_K11_VENTHER.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_VENTHER.gz
wget -O GWAS_ventral_hernia_FinnGen_K11_VENTHER.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_K11_VENTHER.gz.tbi
wget -O GWAS_BMI_FinnGen_BMI_IRN.gz https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_BMI_IRN.gz
wget -O GWAS_BMI_FinnGen_BMI_IRN.gz.tbi https://storage.googleapis.com/finngen-public-data-r9/summary_stats/finngen_R9_BMI_IRN.gz.tbi
