#!/bin/bash
#SBATCH -p defq
#SBATCH --time=60:00
#set -e
cd /data/abattle4/lab_data/GWAS_summary_statistics/SAIGE_UKBB
wget -O GWAS_colon_adenocarcinoma_UKBB_153.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/153.2
wget -O GWAS_hallux_valgus_UKBB_735.3.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/735.3
wget -O GWAS_ulcerative_colitis_UKBB_555.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/555.2
wget -O GWAS_actinic_keratosis_UKBB_702.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/702.1
wget -O GWAS_appendicitis_acute_UKBB_540.11.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/540.11
wget -O GWAS_renal_failure_acute_UKBB_585.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/585.1
wget -O GWAS_alcoholism_UKBB_317.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/317.1
wget -O GWAS_anxiety_disorders_UKBB_300.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/300
wget -O GWAS_angina_pectoris_UKBB_411.3.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/411.3
wget -O GWAS_asthma_UKBB_495.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/495
wget -O GWAS_atrial_fibrillation_UKBB_427.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/427.2
wget -O GWAS_bacterial_infection_other_UKBB_41.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/041
wget -O GWAS_bacterial_pnumonia_UKBB_480.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/480.1
wget -O GWAS_mammary_displasia_benign_UKBB_610.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/610
wget -O GWAS_colon_neoplasm_benign_UKBB_208.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/208
wget -O GWAS_cardiac_arrhythmias_UKBB_427.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/427
wget -O GWAS_cholelithiasis_UKBB_574.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/574.1
wget -O GWAS_chronic_kidney_disease_UKBB_585.3.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/585.3
wget -O GWAS_chronic_sinusitis_UKBB_475.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/475
wget -O GWAS_colorectal_cancer_UKBB_153.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/153
wget -O GWAS_constipation_UKBB_563.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/563
wget -O GWAS_coronary_atherosclerosis_UKBB_411.4.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/411.4
wget -O GWAS_cystitis_UKBB_592.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/592.1
wget -O GWAS_depression_UKBB_296.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/296.2
wget -O GWAS_diaphragmatic_hernia_UKBB_550.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/550.2
wget -O GWAS_lipoprotein_metabolism_disorders_UKBB_272.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/272
wget -O GWAS_intestinal_diverticular_disease_UKBB_562.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/562.1
wget -O GWAS_duodenal_ulcer_UKBB_531.3.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/531.3
wget -O GWAS_endometriosis_UKBB_615.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/615
wget -O GWAS_fracture_at_wrist_and_hand_level_UKBB_804.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/804
wget -O GWAS_gastric_ulcer_UKBB_531.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/531.2
wget -O GWAS_gastroduodenal_ulcer_UKBB_531.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/531.2
wget -O GWAS_glaucoma_UKBB_365.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/365
wget -O GWAS_gout_UKBB_274.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/274.1
wget -O GWAS_abdominal_hernia_UKBB_550.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/550
wget -O GWAS_hypertension_UKBB_401.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/401
wget -O GWAS_inflammatory_bowel_disease_UKBB_555.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/555
wget -O GWAS_inflammatory_diseases_of_female_pelvic_organs_UKBB_614.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/614
wget -O GWAS_inguinal_hernia_UKBB_550.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/550.1
wget -O GWAS_internal_derangement_of_knee_UKBB_835.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/835
wget -O GWAS_intestinal_infectious_diseases_UKBB_8.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/008
wget -O GWAS_ischaemic_heart_disease_UKBB_411.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/411
wget -O GWAS_uterine_leiomyoma_UKBB_218.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/218.1
wget -O GWAS_neoplasm_of_breast_malignant_UKBB_174.11.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/174.11
wget -O GWAS_migraine_UKBB_340.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/340
wget -O GWAS_mood_disorders_UKBB_296.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/296
wget -O GWAS_myocardial_infarction_UKBB_411.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/411.2
wget -O GWAS_nasal_polyps_UKBB_471.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/471
wget -O GWAS_disorders_of_female_genital_tract_noninflammatory_UKBB_619.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/619
wget -O GWAS_obesity_UKBB_278.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/278.1
wget -O GWAS_osteoporosis_UKBB_743.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/743.1
wget -O GWAS_anaemias_unspecified_UKBB_285.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/285
wget -O GWAS_eyelid_disorders_other_UKBB_374.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/374
wget -O GWAS_penis_disorders_other_UKBB_608.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/608
wget -O GWAS_headache_syndromes_other_UKBB_339.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/339
wget -O GWAS_retinal_disorders_other_UKBB_362.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/362
wget -O GWAS_ovarian_cyst_UKBB_628.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/628
wget -O GWAS_pain_in_joint_UKBB_745.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/745
wget -O GWAS_pain_in_limb_UKBB_773.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/773
wget -O GWAS_paroxysmal_tachycardia_UKBB_427.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/427.1
wget -O GWAS_phlebitis_and_thrombophlebitis_UKBB_451.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/451
wget -O GWAS_female_genital_polyp_UKBB_622.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/622
wget -O GWAS_postmenopausal_bleeding_UKBB_627.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/627.1
wget -O GWAS_renal_failure_UKBB_585.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/585
wget -O GWAS_rheumatoid_arthritis_UKBB_714.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/714.1
wget -O GWAS_seborrhoeic_keratosis_UKBB_702.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/702.2
wget -O GWAS_senile_cataract_UKBB_366.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/366.2
wget -O GWAS_sleep_apnoea_UKBB_327.3.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/327.3
wget -O GWAS_sleep_disorders_UKBB_327.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/327
wget -O GWAS_spinal_stenosis_UKBB_720.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/720
wget -O GWAS_type_1_diabetes_UKBB_250.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/250.1
wget -O GWAS_type_2_diabetes_UKBB_250.2.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/250.2
wget -O GWAS_umbilical_hernia_UKBB_550.4.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/550.4
wget -O GWAS_unstable_angina_pectoris_UKBB_411.1.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/411.1
wget -O GWAS_varicose_veins_UKBB_454.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/454
wget -O GWAS_ventral_hernia_UKBB_550.5.PHEWEB.txt.vcf.gz https://pheweb.org/UKB-SAIGE/download/550.5
cd /data/abattle4/lab_data/GWAS_summary_statistics/Neale_lab/highly_heritable_traits
wget https://www.dropbox.com/s/gulqmkaighh8w3b/21001_irnt.gwas.imputed_v3.both_sexes.tsv.bgz?dl=0 -O 21001_irnt.gwas.imputed_v3.both_sexes.tsv.gz
