c.....bin.bash.....SBATCH..p.express.....SBATCH...time.60.00...
#!/bin/bash
#SBATCH -p express
#SBATCH --time=60:00
set -e
source /data/apps/go.sh
cd /data/abattle4/lab_data/GWAS_summary_statistics/PanUKBB/phenotype_flat_files/
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-102-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1160-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1180-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1200-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1210-both_sexes-1210.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1220-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1687-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1717-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-172-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-174-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1747-both_sexes-1.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1226.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1452.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1466.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1473.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20016-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20022-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20110-both_sexes-9.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20116-both_sexes-0.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20117-both_sexes-1.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20127-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20154-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2040-both_sexes-2040.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20409-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20414-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20460-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20479-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20502-both_sexes-20502.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20519-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20548-both_sexes-1.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-208-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2100-both_sexes-2100.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2139-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2149-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22126-both_sexes-22126.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22502-both_sexes-22502.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2257-both_sexes-2257.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-22677-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23100-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23101-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23106-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2316-both_sexes-2316.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2463-both_sexes-2463.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2473-both_sexes-2473.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2492-both_sexes-2492.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-250-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-250.2-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2644-both_sexes-2644.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2664-both_sexes-3.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-272.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-272.11-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2966-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-300-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30000-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30010-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30040-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30060-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30070-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30080-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30100-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30110-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30120-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30130-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30150-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30180-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30190-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30210-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30300-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30530-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3062-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3064-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3143-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3148-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-317-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-351-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3571-both_sexes-3571.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3606-both_sexes-3606.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-361-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-361.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-365-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-366-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3799-both_sexes-3799.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-400-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-401-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-401.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-404-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4080-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-411-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-411.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-411.2-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-411.4-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4195-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-427-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-427.2-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4282-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-454-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-454.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4548-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-455-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4559-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-4598-both_sexes-4598.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-46-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-471-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4825-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-495-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-496-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5085-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-50-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5104-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5110-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5116-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5134-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5157-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-51-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5257-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5262-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-530-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-530.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-530.11-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-531-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-550-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-550.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-550.4-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-562-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-562.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-574-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-574.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-594-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5984-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-6033-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6148-both_sexes-100.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-1.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-3.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-4.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-6.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-1.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-4.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-5.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-7.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-726-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-728.7-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-728.71-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-735.3-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-740-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-740.1-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-788-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-835-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-94-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/phecode-960.2-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-AG-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-C34-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-C44-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-C50-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-D12-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-DBP-both_sexes-combined_medadj_irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-E03-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-E11-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-F32-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-FEV1FVC-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-G56-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-H33-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-H40-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I21-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I48-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I83-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I84-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-IBil-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-J33-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K21-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K40-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K42-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K57-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K80-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-LDLC-both_sexes-medadj_irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M16-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M20-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M72-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M75-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-MAP-both_sexes-combined_irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-MCP-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-N20-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-N81-both_sexes.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-NAP-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-PP-both_sexes-combined_medadj_irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-SBP-both_sexes-combined_irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-eGFRcys-both_sexes-irnt.tsv.bgz
wget -nc https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-whr-both_sexes-irnt.tsv.bgz
