#!/bin/bash
#SBATCH -p express
#SBATCH --time=60:00
set -e
source /data/apps/go.sh
cd /data/abattle4/lab_data/GWAS_summary_statistics/PanUKBB/phenotype_flat_files/
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-102-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1050-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1070-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1080-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1100-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-110001-both_sexes-110001.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1110-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1150-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1160-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1170-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1180-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1190-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1200-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1210-both_sexes-1210.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1220-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1239-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1309-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1319-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1329-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-137-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1408-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1428-both_sexes-0.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1428-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1448-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1458-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1468-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1478-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1488-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1498-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1508-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1518-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1528-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1538-both_sexes-0.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1588-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1618-both_sexes-1618.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1687-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1717-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1737-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1747-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-1757-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1940-both_sexes-1940.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-1970-both_sexes-1970.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2000-both_sexes-2000.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20001-both_sexes-1061.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1065.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1220.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1226.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1452.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1466.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20002-both_sexes-1473.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20003-both_sexes-1140874420.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20003-both_sexes-1140883504.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20016-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20022-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20116-both_sexes-0.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20117-both_sexes-2.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20127-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20154-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2020-both_sexes-2020.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2040-both_sexes-2040.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20409-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20414-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20441-both_sexes-20441.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20453-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20460-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20479-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20480-both_sexes-20480.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20502-both_sexes-20502.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-20512-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20530-both_sexes-20530.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20531-both_sexes-20531.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-20548-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2080-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2100-both_sexes-2100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2129-both_sexes-2129.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2139-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2149-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2178-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22126-both_sexes-22126.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2217-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2237-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22502-both_sexes-22502.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2257-both_sexes-2257.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22609-both_sexes-2.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-22620-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2267-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23100-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23101-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-23106-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2316-both_sexes-2316.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2335-both_sexes-2335.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2463-both_sexes-2463.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2473-both_sexes-2473.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2644-both_sexes-2644.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2654-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-2664-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-2966-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30000-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30010-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30020-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30040-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30060-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30070-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30080-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30100-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30110-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30120-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30130-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30180-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30190-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30210-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30260-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30300-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30510-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-30530-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3062-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3064-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3143-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3148-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3393-both_sexes-3393.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3571-both_sexes-3571.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3606-both_sexes-3606.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-3761-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-3799-both_sexes-3799.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-400-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-404-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4080-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-41248-both_sexes-1000.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4195-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4282-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4290-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-4294-both_sexes-0.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-4559-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-46-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-4979-both_sexes-4979.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-5001-both_sexes-5001.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5085-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-50-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5104-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5105-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5110-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5116-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5134-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5157-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5257-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5263-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-5984-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-6033-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6142-both_sexes-6.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6143-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6143-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6144-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6144-both_sexes-5.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6145-both_sexes-6.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6146-both_sexes-100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6148-both_sexes-100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6148-both_sexes-2.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6148-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6149-both_sexes-6.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6152-both_sexes-8.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6154-both_sexes-3.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6154-both_sexes-6.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-5.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-6.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6159-both_sexes-7.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6160-both_sexes-100.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6160-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6162-both_sexes-2.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6164-both_sexes-1.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6164-both_sexes-2.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6164-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6164-both_sexes-5.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/categorical-6179-both_sexes-4.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-728-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-845-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-874-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-924-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-94-both_sexes-irnt.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-C44-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-C50-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-D12-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-E03-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-E11-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-E66-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-F32-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-G47-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-G56-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-H33-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I25-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I48-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I83-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-I84-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-J33-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-J44-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K40-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K42-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K44-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K52-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K57-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-K80-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M16-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M17-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M20-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M51-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M72-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-M75-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-N20-both_sexes.tsv.bgz
wget https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/icd10-N81-both_sexes.tsv.bgz
