#!/bin/bash
#SBATCH --job-name=no_overlap_part1
#SBATCH --time=20:0:0
#SBATCH --partition=shared
#SBATCH  --mem=10G
source /data/apps/go.sh ### for safety reasons 
set -e
cd /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration
mkdir -p  simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U101_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U101_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U101_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U101_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U101_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U101_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U102_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U102_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U102_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U102_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U102_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U102_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U103_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U103_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U103_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U103_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U103_MAF-mix_eur_N-mixed_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U103_MAF-mix_eur_N-mixed_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U101_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U102_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V102_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V102_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V103_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V103_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -f -s  simulating_factors/custom_easy/yaml_files/final_sims_june_2024/no_overlap//V101_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/no_overlap/V101_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
