#!/bin/bash
#SBATCH --job-name=special_no_overlap_part3
#SBATCH --time=15:0:0
#SBATCH --partition=shared
#SBATCH  --mem=10G
source /data/apps/go.sh ### for safety reasons 
set -e
cd /scratch16/abattle4/ashton/snp_networks/custom_l1_factorization/manuscript_analyses/simulations/2_factor_based/
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U103_MAF-mix_eur_N-2e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U101_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U102_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U102_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U102_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U102_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U103_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U103_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U103_MAF-mix_eur_N-1e+05_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U103_MAF-mix_eur_N-1e+05_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U101_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U101_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U101_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U101_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U102_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U102_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U102_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U102_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U103_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U103_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U103_MAF-mix_eur_N-50000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U103_MAF-mix_eur_N-50000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U101_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U101_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U101_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U101_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U102_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U102_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U102_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U102_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U103_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U103_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U103_MAF-mix_eur_N-10000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U103_MAF-mix_eur_N-10000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U101_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U101_MAF-mix_eur_N-5000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U101_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U101_MAF-mix_eur_N-5000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U102_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U102_MAF-mix_eur_N-5000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U102_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U102_MAF-mix_eur_N-5000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V111_U103_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V111_U103_MAF-mix_eur_N-5000_RHO-none_No-none/ 
bash src/runSimulation.sh -a  /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration//simulating_factors/custom_easy/yaml_files/final_sims_june_2024/special_no_overlap//V110_U103_MAF-mix_eur_N-5000_RHO-none_No-none.yml /scratch16/abattle4/ashton/snp_networks/scratch/cohort_overlap_exploration/simulating_factors/custom_easy/simulation_outputs/final_sims_june_2024/special_no_overlap/V110_U103_MAF-mix_eur_N-5000_RHO-none_No-none/ 
